### ISSUE TITLE
Error in Debug: Get state using data format 'cli'

### ISSUE THREAD

**Issue by excilsploft** [cisco/cisco-network-puppet-module#344]
When doing a puppet run we get the following error (in debug mode)

Debug:   with context:
    interface port-channel1
Debug:   to get value:     /^switchport mode private-vlan (.*)$/
Debug: Input (cli_show_ascii): 'show running interface all'
Debug: Massaging '' (nil)
Debug: Default: disabled
Debug: Get state using data format 'cli'
Debug:   executing command:
    show running interface all
Debug:   with context:
    interface port-channel1
Debug:   to get value:     /^switchport trunk allowed vlan (.*)$/
Debug: Input (cli_show_ascii): 'show running interface all'
Debug: Massaging '["500-528,530,532,534,587,590-593", "add 597"]' (["500-528,530,532,534,587,590-593", "add 597"])
Debug: Storing state
Debug: Stored state in 0.12 seconds
Error: Failed to apply catalog: Expected zero/one value but got '["500-528,530,532,534,587,590-593", "add 597"]'

Our interface port channel looks like this

interface port-channel1
  description vPC peer link
  switchport mode trunk
  switchport trunk allowed vlan 500-528,530,532,534,587,590-593
  switchport trunk allowed vlan add 597
  spanning-tree port type network
  vpc peer-link

**Comment by mikewiebe** [comment]
Hello @excilsploft, thanks for your query.  Couple of questions.
- Which cisco puppet module version and cisco_node_utils version are you using?
- Can you include your manifest?

**Comment by excilsploft** [comment]
Sorry for the prior lack of details here is the info:
cisco_node_utils (1.3.0)
puppetlabs-ciscopuppet (1.3.1)

simple manifest as we are learning and trying to figure this all out

>> cisco_interface {'port-channel120':
>>   ensure                        => 'present',
>>   description                   => 'Configured with Puppet',
>>   switchport_mode               => 'trunk',
>>   mtu                           => 9216,
>>   switchport_trunk_allowed_vlan => '2501,2500',
>>   switchport_trunk_native_vlan  => 2500,
>> }

**Comment by robert-w-gries** [comment]
This line of config on your interface is leading to the error: `switchport trunk allowed vlan add 597`

The reason you are seeing the error is that our regexp for detecting VLAN IDs does not properly exclude keywords such as `add` or `remove`.

```bash
Debug: to get value: /^switchport trunk allowed vlan (.*)$/
Debug: Input (cli_show_ascii): 'show running interface all'
Debug: Massaging '["500-528,530,532,534,587,590-593", "add 597"]' (["500-528,530,532,534,587,590-593", "add 597"])
```

There should only be one match of `500-528,530,532,534,587,590-593`, but our regexp also matches `switchport trunk allowed vlan (add 597)`.

@mikewiebe We will need to fix the regexp so that it only matches VLAN IDs.

**Comment by mikewiebe** [comment]
@excilsploft We are working on the issue and will provide the official fix in an upcoming release.  In the mean time, we will provide a workaround for you once we have completed our testing of the fix.

**Comment by excilsploft** [comment]
Thanks
