### ISSUE TITLE
vlan attribute mode error

### ISSUE THREAD

**Issue by excilsploft** [cisco/cisco-network-puppet-module#345]
Details:
cisco_node_utils (1.3.0)
puppetlabs-ciscopuppet (1.3.1)
NXOS: version 7.0(3)I2(2a)
cisco Nexus9000

>Error: /Stage[main]/Profiles::Cisco::Vlans/Cisco_vlan[2500]: Could not evaluate: Feature 'vlan', attribute >'mode', operation 'setter' is unsupported on this node
>Notice: /Stage[main]/Profiles::Cisco::Vlans/Cisco_vlan[2501]/mode: mode changed '' to 'CE'
>Error: /Stage[main]/Profiles::Cisco::Vlans/Cisco_vlan[2501]: Could not evaluate: Feature 'vlan', attribute >'mode', operation 'setter' is unsupported on this node

Manifest looks like:

>>class profiles::cisco::vlans {
>>
>>  cisco_vlan { '2500':
>>      ensure    => 'present',
>>      vlan_name => 'vlan_2500',
>>      shutdown  =>  false,
>>      state     => 'active',
>>      mode      => 'CE',
>>  }
>>
>>  cisco_vlan { '2501':
>>      ensure    => 'present',
>>      vlan_name => 'vlan_2501',
>>      shutdown  =>  false,
>>      state     => 'active',
>>      mode      => 'CE',
>>  }
>>
>>}

**Comment by mikewiebe** [comment]
@excilsploft The `mode` property is only supported on the `n5k, n6k and n7k`.  Please see our main README for the `cisco_vlan` provider.
- https://github.com/cisco/cisco-network-puppet-module/blob/master/README.md#caveats-13

**Comment by excilsploft** [comment]
apologies for that sorry RTFM bites me again :)
