### ISSUE TITLE
undefined method `switchport_pvlan_trunk_native_vlan' for #<Cisco::Interface:0x000000044b5740>

### ISSUE THREAD

**Issue by ambientmf** [cisco/cisco-network-puppet-module#356]
Using latest "develop" build for the cisco puppet module. 1.5.2-1.cisco_wrlinux5 puppet agent. Testing on N9K running version 7.0(3)I2(2b). Puppet reporting this error using a relatively simple manifest:

root@pod1-spine5:[/] # puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for pod1-spine5
Info: Applying configuration version '1467742002'
Error: Failed to apply catalog: undefined method `switchport_pvlan_trunk_native_vlan' for #<Cisco::Interface:0x0000000475fae0>

I'm no Ruby programmer but I see that it IS defined in cisco_interface.rb under lib/puppet/types in the ciscopuppet module. Stumped with this error. Manifest below:

```ruby
class ciscopuppet::demo {
    cisco_interface { 'test-lo0':
        ensure                  => present,
        interface               => 'loopback0',
        shutdown                => false,
        description             => 'puppet - router ID',
        ipv4_address            => '10.0.0.101',
        ipv4_netmask_length     => 32,
        ipv4_pim_sparse_mode    => true,
    }
    cisco_ospf { 'UNDERLAY':
        ensure  => present,
    }
    # <process name or ID> <VRF> <Area ID>
    cisco_ospf_area { 'UNDERLAY default 0.0.0.1':
        ensure              => present,
        authentication      => 'md5',
        range               => [['10.0.0.0/24'], ['10.0.1.0/24']],
        nssa                => true,
    }
    # <interface resource name> <ospf resource name>
    cisco_interface_ospf { 'test-lo0 UNDERLAY':
        ensure                          => present,
        interface                       => 'test-lo0',
        ospf                            => 'UNDERLAY',
        area                            => '0.0.0.1',
        message_digest                  => true,
        message_digest_key_id           => 1,
        message_digest_algorithm_type   => 'md5',
        message_digest_encryption_type  => 'cisco_type_7',
        message_digest_password         => 'e3b5189d66d7ed80',
    }
```

**Comment by chrisvanheuveln** [comment]
@ambientmf Looks like you have a module / gem mismatch. The **ciscopuppet module** has a dependency on the **cisco_node_utils ruby gem**. The node utils APIs are the interface between the NX-OS CLI and the Puppet Types & Providers. 

It's important to keep these in sync and this is usually automatic if your manifest is set up to [install with a manifest](https://github.com/cisco/cisco-network-puppet-module#cisco_node_utils-ruby-gem), which will pull the latest release version of the `cisco_node_utils` gem from [rubygems.org](https://rubygems.org/gems/cisco_node_utils).

Production users will typically use the latest release version of the ciscopuppet module found on [puppetforge](https://forge.puppet.com/puppetlabs/ciscopuppet) which will keep these matched up.

However, you're using the `develop` branch, which is pre-release code and I'm guessing you've mistakenly installed the cisco_node_utils release gem with it instead of a gem from the `develop` branch. If that's the case then just match them up one of these ways:

Option A) Install the current ciscopuppet release module on your puppetmaster to match the node utils gem that's installed on your node:

```
1. Remove the 'develop' module
puppet module uninstall puppetlabs-ciscopuppet

2. Install the release module from puppet forge
puppet module install puppetlabs-ciscopuppet
```

-OR-

Option B) Build a `develop` branch node utils gem and install that on your node to match the ciscopuppet module that's installed on your puppetmaster. To build the gem do the following:

```
1. Clone the node utils repo and checkout the develop branch:

git clone https://github.com/cisco/cisco-network-node-utils.git
git checkout develop

2. cd to the repo directory and build the gem:

cd cisco-network-node-utils
gem build cisco_node_utils.gemspec
      Successfully built RubyGem
      Name: cisco_node_utils
      Version: 1.0.1
      File: cisco_node_utils-1.0.1.gem

3. Copy the new gem to your NX-OS device, uninstall the existing gem and install the new one:
(example showing the native bash shell environment)

n9k# gem list cisco_node_utils
n9k# gem uninstall cisco_node_utils
n9k# gem install --local /bootflash/cisco_node_utils-1.0.1.gem
```

**Comment by ambientmf** [comment]
Thanks Chris. I'll install the development gem and close out this issue. I
was previously running the 1.3.1 release of the module and re-used the
1.3.0 release of the cisco_node_utils gem...makes perfect sense.

I'm just in testing phase right now and the develop branch
had cisco_ospf_area type that was missing for our use case.

On Wednesday, 6 July 2016, Chris Van Heuveln <notifications@github.com>
wrote:

> @ambientmf <https://github.com/ambientmf> Looks like you have a module /
> gem mismatch. The *ciscopuppet module* has a dependency on the *cisco_node_utils
> ruby gem*. The node utils APIs are the interface between the NX-OS CLI
> and the Puppet Types & Providers.
>
> It's important to keep these in sync and this is usually automatic if your
> manifest is set up to install with a manifest
> <https://github.com/cisco/cisco-network-puppet-module#cisco_node_utils-ruby-gem>,
> which will pull the latest release version of the cisco_node_utils gem
> from rubygems.org <https://rubygems.org/gems/cisco_node_utils>.
>
> Production users will typically use the latest release version of the
> ciscopuppet module found on puppetforge
> <https://forge.puppet.com/puppetlabs/ciscopuppet> which will keep these
> matched up.
>
> However, you're using the develop branch, which is pre-release code and
> I'm guessing you've mistakenly installed the cisco_node_utils release gem
> with it instead of a gem from the develop branch. If that's the case then
> just match them up one of these ways:
>
> Option A) Install the current ciscopuppet release module on your
> puppetmaster to match the node utils gem that's installed on your node:
>
> 1. Remove the 'develop' module
> puppet module uninstall puppetlabs-ciscopuppet
>
> 2. Install the release module from puppet forge
> puppet module install puppetlabs-ciscopuppet
>
> -OR-
>
> Option B) Build a develop branch node utils gem and install that on your
> node to match the ciscopuppet module that's installed on your puppetmaster.
> To build the gem do the following:
>
> 1. Clone the node utils repo and checkout the develop branch:
>
> git clone https://github.com/cisco/cisco-network-node-utils.git
> git checkout develop
>
> 2. cd to the repo directory and build the gem:
>
> cd cisco-network-node-utils
> gem build cisco_node_utils.gemspec
>       Successfully built RubyGem
>       Name: cisco_node_utils
>       Version: 1.0.1
>       File: cisco_node_utils-1.0.1.gem
>
> 3. Copy the new gem to your NX-OS device, uninstall the existing gem and install the new one:
> (example showing the native bash shell environment)
>
> n9k# gem list cisco_node_utils
> n9k# gem uninstall cisco_node_utils
> n9k# gem install --local /bootflash/cisco_node_utils-1.0.1.gem
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cisco/cisco-network-puppet-module/issues/356#issuecomment-230753330>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF8VhAwtvYOXqnsS8Zs1jNGkgOHhchchks5qS5qmgaJpZM4JFYw8>
> .
>


-- 
Thomas Cooper
Phone: (416) 668-9336
Email: thomascooperca@gmail.com
