### ISSUE TITLE
Update documentation for automating gem installations

### ISSUE THREAD

**Issue by ambientmf** [cisco/cisco-network-puppet-module#370]
Hi all,
Just thought I'd open this issue as an FYI. I believe the following documentation should be updated for getting the dependent Ruby gems pushed via the package provider from a Puppet master onto a N9K switch. Following the example manifest in the README-gem-install document did not yield successful gem installation via a puppet run on a Nexus 9K running the bash shell agent.

https://github.com/cisco/cisco-network-puppet-module/blob/develop/docs/README-gem-install.md#gem-persistence

The provider that needs to be used is "puppet_gem". 
See example manifest below:

class ciscopuppet::general {
    package { 'net_http_unix':
        ensure          => present,
        provider        => 'puppet_gem',
        source          => 'http://gemserver.local:8808',
    }
    package { 'cisco_node_utils' :
        ensure          => present,
        provider        => 'puppet_gem',
        source          => 'http://gemserver.local:8808',
    }

One other point worth mentioning is that the Ruby gem API underwent some changes (from some quick Google'ing) and so a newer Ruby version is required to be able to use the native "gem server" as a local gem host. I have this working using Ruby 2.0.0p598 compiled on a RHEL7 server (which is also my puppet master for our setup). In our environment, our switches are not able to reach directly out to the Internet via our proxies so I hacked this together for an internal gem host. 

[root@gemserver bin]# ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

(gem server log below)
pod2-switch1- - [22/Jul/2016:10:50:08 EDT] "GET /gems/**net_http_unix-0.2.1.gem** HTTP/1.1" 200 11776 - -> /gems/net_http_unix-0.2.1.gem
pod2-switch1- - [22/Jul/2016:10:52:30 EDT] "GET /latest_specs.4.8.gz HTTP/1.1" 200 610 - -> /latest_specs.4.8.gz
pod2-switch1- - [22/Jul/2016:10:52:30 EDT] "GET /quick/Marshal.4.8/cisco_node_utils-1.3.1.gemspec.rz HTTP/1.1" 200 633 - -> /quick/Marshal.4.8/cisco_node_utils-1.3.1.gemspec.rz
pod2-switch1- - [22/Jul/2016:10:54:37 EDT] "HEAD /api/v1/dependencies HTTP/1.1" 404 0 - -> /api/v1/dependencies
pod2-switch1 - - [22/Jul/2016:10:54:37 EDT] "GET /specs.4.8.gz HTTP/1.1" 200 642 - -> /specs.4.8.gz
pod2-switch1 - - [22/Jul/2016:10:54:37 EDT] "GET /gems/**cisco_node_utils-1.3.1.gem** HTTP/1.1" 200 400384 - -> /gems/cisco_node_utils-1.3.1.gem

**Comment by chrisvanheuveln** [comment]
Hi. Thanks for the feedback. We're not seeing the package provider issue you're describing on any of our current platforms or environments ( `provider => 'gem'` installs both gems fine). 

Can you provide some add'l information about your setup? i.e. `show version` on your 9k; `puppet --version` in the agent bash shell and on the puppetmaster; `puppet module list` on your puppetmaster. Thanks,
Chris

**Comment by ambientmf** [comment]
Hi Chris. Here's the requested info:

pod2-switch1# show version
Cisco Nexus Operating System (NX-OS) Software
Software
  BIOS: version 07.34
  NXOS: version 7.0(3)I2(2d)
  BIOS compile time:  08/11/2015
  NXOS image file is: bootflash:///nxos.7.0.3.I2.2d.bin
  NXOS compile time:  4/24/2016 13:00:00 [04/24/2016 20:28:19]


Hardware
  cisco Nexus9000 C9396PX Chassis 
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401936 kB of memory.
  Processor Board ID SAL18443BX0

  Device name: pod2-switch1
  bootflash:    7906304 kB
Kernel uptime is 27 day(s), 13 hour(s), 51 minute(s), 46 second(s)

Last reset at 874862 usecs after  Wed Jul 13 23:49:10 2016

root@pod2-switch1#puppet --version
4.5.2

root@master:[~] # puppet module list
/etc/puppetlabs/code/environments/production/modules
â”œâ”€â”€ puppetlabs-ciscopuppet (v1.3.2)
â””â”€â”€ puppetlabs-netdev_stdlib (v0.11.1)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules
â”œâ”€â”€ puppetlabs-pe_accounts (v2.0.2-6-gd2f698c)
â”œâ”€â”€ puppetlabs-pe_concat (v1.1.2-7-g77ec55b)
â”œâ”€â”€ puppetlabs-pe_console_prune (v0.1.1-9-gfc256c0)
â”œâ”€â”€ puppetlabs-pe_hocon (v2016.2.0)
â”œâ”€â”€ puppetlabs-pe_inifile (v1.1.4-16-gcb39966)
â”œâ”€â”€ puppetlabs-pe_java_ks (v1.2.4-37-g2d86015)
â”œâ”€â”€ puppetlabs-pe_nginx (v2016.2.0-rc2)
â”œâ”€â”€ puppetlabs-pe_postgresql (v2016.2.0)
â”œâ”€â”€ puppetlabs-pe_puppet_authorization (v2016.2.0-rc1)
â”œâ”€â”€ puppetlabs-pe_r10k (v2016.2.0)
â”œâ”€â”€ puppetlabs-pe_razor (v1.0.0)
â”œâ”€â”€ puppetlabs-pe_repo (v2016.2.0)
â”œâ”€â”€ puppetlabs-pe_staging (v2015.3.0)
â””â”€â”€ puppetlabs-puppet_enterprise (v2016.2.0-9-gc771e9c)

I just checked the Puppet docs for the package provider, looks like this provider was added in Puppet version 4.4

**Comment by mikewiebe** [comment]
@ambientmf While prepping for our upcoming release, I re-verified our workflow and don't see the problem you are seeing.  We provide the following guidance in our main `README.md` file for installing the gem via puppet manifest.

https://github.com/cisco/cisco-network-puppet-module/tree/develop#automatic-gem-install-using-ciscopuppetinstall

Following this process, I am able to install the gem on my n9k device.

```
root@dt-n9k5-1#gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
deep_merge (1.0.1)
facter (3.4.1)
hiera (3.2.1)
hocon (0.9.3)
io-console (0.4.3)
json (1.8.1)
minitest (4.7.5)
net-ssh (2.9.2)
psych (2.0.5)
puppet (4.7.0)
rake (10.1.0)
rdoc (4.1.0)
semantic_puppet (0.1.2)
stomp (1.3.3)
test-unit (2.1.9.0)


root@dt-n9k5-1#puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for dt-n9k5-1.cisco.com
Warning: Found multiple default providers for package: yum, puppet_gem, pip3; using yum
Info: Applying configuration version '1475503321'
Notice: /Stage[main]/Ciscopuppet::Install/Package[cisco_node_utils]/ensure: created
Notice: Applied catalog in 97.03 seconds
root@dt-n9k5-1#

root@dt-n9k5-1#gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
cisco_node_utils (1.3.0)
deep_merge (1.0.1)
facter (3.4.1)
hiera (3.2.1)
hocon (0.9.3)
io-console (0.4.3)
json (1.8.1)
minitest (4.7.5)
net-ssh (2.9.2)
net_http_unix (0.2.2)
psych (2.0.5)
puppet (4.7.0)
rake (10.1.0)
rdoc (4.1.0)
semantic_puppet (0.1.2)
stomp (1.3.3)
test-unit (2.1.9.0)
root@dt-n9k5-1#
```

This installs both `net_http_unix` and `cisco_node_utils`.

Here is my manifest:

```
puppetmaster:/etc/puppetlabs/code/environments/production/manifests# cat site.pp 
node 'default' {
  include ciscopuppet::install
}

puppetmaster:/etc/puppetlabs/code/environments/production/manifests# 
```
```

**Comment by ambientmf** [comment]
Mike,
Thanks for the info.
I think this is specific to the Puppet server version.
From 3.8 to 4.0 and later, the "puppet_gem" provider was added.
See here:

https://docs.puppet.com/puppet/3.8/reference/type.html#package-providers
https://docs.puppet.com/puppet/4.0/reference/type.html#package-providers

It seems to me that I'm testing using a newer version of Puppet server. It might be worthwhile pointing this out in the docs, especially for the novice Puppet users (such as myself :) ). Unless you have any other background to add, we can close this issue.

**Comment by mikewiebe** [comment]
@ambientmf Thanks for the feedback!  It's always helpful to understand different user workflows.  The server version we are using is `4.2.2` which should be recent enough.

```
puppetmaster:~# puppet --version
4.2.2
puppetmaster:~# 
```

I don't have any additional data to provide since we have not been able to recreate the issue you describe with the `gem` provider.  I plan to close this for now, but we will make sure to add any relevant version information in future releases.
