### ISSUE TITLE
Absent resourcetypes in module

### ISSUE THREAD

**Issue by TeunRoefs** [cisco/cisco-network-puppet-module#420]
Hi there,

Currently in the process of rewriting a Cisco N3k config to Puppet DSL and was wondering if there are a couple of options in the config that currently cannot be set using resource types.

I've encountered the following:
* prefix-list
* class-map
* route-map (I've seen PR)
* vrf
** graceful-restart
** grace-period
** ip name-server
** ip route
** ip domain-name
* policy-map
* router_bgp
** vrf - router_id

Can anyone confirm this and if so, do I have to use cisco_command_config to configure these resources for now?

**Comment by mikewiebe** [comment]
@TeunRoefs  Thank you for your interest in the open source cisco-network-puppet-module!
 
This module is designed to grow with contributions from the Open Source community, Cisco, and Puppet Labs.
 
We welcome and encourage users to contribute to the expansion of the module.  If there is a feature that is currently not supported, please consider the following options:
 
1. Add support for the missing feature(s) and submit a pull request for it to be integrated into the module.
    - https://github.com/cisco/cisco-network-node-utils/blob/develop/CONTRIBUTING.md
    - https://github.com/cisco/cisco-network-puppet-module/blob/master/CONTRIBUTING.md
2. Reach out to your Cisco representative and ask for the feature to be added to the roadmap.
3. Use the cisco_command_config provider for features that do not have custom type/provider support.
    - User Documentation: https://github.com/cisco/cisco-network-puppet-module#type-cisco_command_config
