### ISSUE TITLE
Feature request; "load-interval" for cisco_interface

### ISSUE THREAD

**Issue by tomcooperca** [cisco/cisco-network-puppet-module#423]
Hi,
Can you please add the "load-interval" attribute to the cisco_interface type?
I need to manage these settings to keep interface timers consistent across all our switches. Thanks!

**Comment by mikewiebe** [comment]
@tomcooperca We can certainly add that as a managed attribute.  We will schedule this work in an upcoming sprint and update the case when the work is complete.

**Comment by tomcooperca** [comment]
@mikewiebe thank you!

**Comment by mikewiebe** [comment]
@tomcooperca Code has been committed for this feature into our develop branch and will be part of the `1.6.0` version of the puppet module.
