### ISSUE TITLE
LACP not supported on cisco_interface_channel_group resource

### ISSUE THREAD

**Issue by tomcooperca** [cisco/cisco-network-puppet-module#432]
The cisco_interface_channel_group provider does not configure LACP modes and assumes a static port-channel only.
When deploying Puppet to brownfield, this presents a problem as most port-channels are using LACP.

Can we expose a "mode" attribute for the channel-group configurations? With only static port channels supported, we actually cannot use this type. Thanks. PS: See logs below, this is error'ing out because we are using LACP for the vPC peer-link port-channel + member links

Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Applying configuration version 'b3c9659d41e58069ddb8f44cdc687c1538db4c40'
Notice: /Stage[main]/Cisco_datacentre::Vpc/Cisco_interface_channel_group[Ethernet1/53]/channel_group: channel_group changed 'false' to '100'
Error: /Stage[main]/Cisco_datacentre::Vpc/Cisco_interface_channel_group[Ethernet1/53]: Could not evaluate: [interface_channel_group ethernet1/53] The command ' channel-group 100 force' was rejected with error:
Cannot add on-mode port to active-mode port-channel

Notice: /Stage[main]/Cisco_datacentre::Vpc/Cisco_interface_channel_group[Ethernet1/54]/channel_group: channel_group changed 'false' to '100'
Error: /Stage[main]/Cisco_datacentre::Vpc/Cisco_interface_channel_group[Ethernet1/54]: Could not evaluate: [interface_channel_group ethernet1/54] The command ' channel-group 100 force' was rejected with error:
Cannot add on-mode port to active-mode port-channel

**Comment by mikewiebe** [comment]
@tomcooperca We can add this property.  I will get this work scheduled in the upcoming sprint that starts next week.

**Comment by tomcooperca** [comment]
@mikewiebe do you mind taking a look at this PR?
I think node_utils repo might be more approriate for this issue. The type/provider code looks to be fairly simple to add but there's API changes needed for the channel_group. 

https://github.com/cisco/cisco-network-node-utils/pull/529

This is just my attempt, I fully expect that it will need some work to flesh this out more fully.

**Comment by mikewiebe** [comment]
@tomcooperca Thanks for contributing to the module!  Let me take a look and verify it against our CI.

**Comment by mikewiebe** [comment]
@tomcooperca I am going to close this issue since the PR you reference above is now merged.  Once you have the PR for the puppet side we can continue the integration.  Let me know if you have any questions on the type/provider part.
