### ISSUE TITLE
cisco_vpc_domain delay restore prop not accepting valid values

### ISSUE THREAD

**Issue by tomcooperca** [cisco/cisco-network-puppet-module#446]
https://github.com/cisco/cisco-network-puppet-module/blob/develop/lib/puppet/type/cisco_vpc_domain.rb#L145

This type checks for values only between 240 and 3600. However, via CLI, you can configure a lower threshold. Need to update the munging on this type. See below:

```
switch(config-vpc-domain)# delay restore interface-vlan ?
  <1-3600>  Delay in bringing up the interface-vlan (in seconds)

switch(config-vpc-domain)# delay restore ?
  <1-3600>        Delay in bringing up the vPC links (in seconds)
  interface-vlan  Delay in bringing-up interface-vlan

switch(config-vpc-domain)# delay restore 30
switch(config-vpc-domain)# delay restore interface-vlan 30
```

**Comment by mikewiebe** [comment]
@tomcooperca I plan to just remove the range check and let the cli reject.  Are you ok with that?

**Comment by tomcooperca** [comment]
Yeah, that's fine with me.
