### ISSUE TITLE
New aggregate-address property for cisco_bgp_af type

### ISSUE THREAD

**Issue by MatteoCampolmi** [cisco/cisco-network-puppet-module#452]
At the moment the cisco_bgp_af type doesn't expose a property to define an 'aggregate-address network/mask summary-only' advertisement.

This setting is critical in our brownfield VXLAN implementation since it allows us to automatically filter the leaking of host routes outside of the fabric.

Would it be possible to have it added?

Thanks

**Comment by mikewiebe** [comment]
@MatteoCampolmi Thanks for your interest in the module.  That should not be a problem.  We will schedule this in an upcoming iteration.

**Comment by MatteoCampolmi** [comment]
@mikewiebe Thank you, that will simplify a lot our deployment.

**Comment by mikewiebe** [comment]
@MatteoCampolmi This work is now complete from our side.  Please test out the changes and send us any feedback.

**Comment by MatteoCampolmi** [comment]
@mikewiebe in which stable release would this new feature be introduced? When would it be scheduled for release?

**Comment by mikewiebe** [comment]
This will be in the `1.7.0` release which will be out in a few weeks.  You can build a custom gem/puppet module sooner if you want to test it though.

**Comment by saichint** [comment]
Closing this enhancement. It will be available in 1.7.0
