### ISSUE TITLE
Are port profiles going to be supported?

### ISSUE THREAD

**Issue by onyxmaster** [cisco/cisco-network-puppet-module#488]
Hi!

Are port profiles for interfaces going to be supported? We use them extensively in static configuration, they would be very helpful for dynamic configuration too.

Thank you,
Aristarkh Zagorodnikov

**Comment by mikewiebe** [comment]
@onyxmaster Thank you for your interest in the cisco-network-puppet-module!
 
This module is designed to grow with contributions from the Open Source community, Cisco, and Puppet Labs.
 
We welcome and encourage users to contribute to the expansion of the module.  If there is a feature that is currently not supported, please consider the following options:
 
1. Add support for the missing feature(s) and submit a pull request for it to be integrated into the module.
    - https://github.com/cisco/cisco-network-node-utils/blob/develop/CONTRIBUTING.md
    - https://github.com/cisco/cisco-network-puppet-module/blob/master/CONTRIBUTING.md
2. Reach out to your Cisco representative and ask for the feature to be added to the roadmap.
3. Use the cisco_command_config provider for features that do not have custom type/provider support.
    - User Documentation: https://github.com/cisco/cisco-network-puppet-module#type-cisco_command_config
