### ISSUE TITLE
Very slow execution when managing interfaces

### ISSUE THREAD

**Issue by bsauvajon** [cisco/cisco-network-puppet-module#496]
Hi,
I've started to use the ciscopuppet module to manage configuration on a nexus 5672UP with 12 FEX 2232TM-E, using Open Agent Container.
Firstly, I've successfully managed local users, and now I'm starting to manage some interfaces configuration.

As soon as I declared my first interface, manifest execution time has gone from 30 seconds to 900 seconds.
Debug shows puppet takes a very long time to scan and build the list of existing interface ressources on the switch. Each interface discovery seems to take between 1 and 2 seconds, and when adding physical interfaces, vlan interfaces an port-channel, I have more than 500 interfaces declared. Is there a way to accelerate this step ?

**Comment by mikewiebe** [comment]
@bsauvajon Thanks for your interest in the module.  We will look into this problem to see if we can improve the performance.  Would you be willing to share your manifest and debug logs?

**Comment by bsauvajon** [comment]
@mikewiebe No problem to share manifest and debug logs, how can I send it ?

**Comment by mikewiebe** [comment]
@bsauvajon Let me try and recreate it in my environment first with the information you have already provided and if I cannot then I will reach out to you for more information.

**Comment by mikewiebe** [comment]
@bsauvajon Just an update on this issue.  I have been able to recreate the problem and am investigating potential solutions.

**Comment by mikewiebe** [comment]
Resolved by https://github.com/cisco/cisco-network-puppet-module/pull/561
