### ISSUE TITLE
cisco_interface 100GB speed setting incorrect

### ISSUE THREAD

**Issue by gkevlin** [cisco/cisco-network-puppet-module#497]
https://github.com/cisco/cisco-network-puppet-module/blob/develop/lib/puppet/type/cisco_interface.rb
 
Lines 183-187
```
 newproperty(:speed) do
    desc "Configure the speed between interfaces. Default value is 'auto'."

    newvalues(:auto, 10, 100, 1000, 10_000, **1_000_000**, 40_000, :default)
  end # property speed
```

1_000_000 is not a valid value.  For 100Gb interfaces the value should be 100_000.

If possible could this be fixed as part of the 1.9 branch with a 1.9.1 tag release?

Thanks,
George Kevlin

**Comment by shermdog** [comment]
@gkevlin Thanks for the report.  We'll work on getting this fixed up.  I suspect it will be part of the upcoming 1.10.0 release.

cc @mikewiebe

**Comment by mikewiebe** [comment]
@gkevlin @shermdog Is correct that we can include this as part of the `1.10` release that will be out in a few weeks.

**Comment by mikewiebe** [comment]
Fixed in https://github.com/cisco/cisco-network-puppet-module/pull/499
