### ISSUE TITLE
cisco_bgp && timer_bgp_hold

### ISSUE THREAD

**Issue by henriots** [cisco/cisco-network-puppet-module#522]
Hello!

Trying to set BGP timer for Nexus 5672UP and getting error:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'timer_bgp_hold' at /etc/puppetlabs/code/environments/production/manifests/classes.pp:280 on Cisco_bgp[65201]`

```
cisco_bgp { "${as_self}":
	ensure	=> present,
	router_id	=> "${router_id}",
	bestpath_aspath_multipath_relax	=> "true",
	fast_external_fallover	=> "true",
	graceful_restart	=> "true",
	log_neighbor_changes	=> "true",
	timer_bgp_keepalive	=> "3",
	timer_bgp_hold	=> "9",
}
```
I checked the "cisco_bgp" code and changing "timer_bgp_hold" to "timer_bgp_holdtime" works, so documentation is misleading @ https://github.com/cisco/cisco-network-puppet-module#timer_bgp_hold.

**Comment by saichint** [comment]
I am closing this issue as we have addressed it in README and the PR is merged already,
