### ISSUE TITLE
Manage mgmt0 interface ?

### ISSUE THREAD

**Issue by JBaptisme** [cisco/cisco-network-puppet-module#528]
Hello,

Management interface (mgmt0) seem not be  manageable by Puppet. 
Indeed manage this interface can be dangerous.
Is it a feature or an issue ?.

Indeed my actual process is:
1- Provision a switch with POAP and an static conf (with a "templated IP adress)
2- Install puppet on the switch
3- Retrie catalog for node 

So in action 3, mgmt IP should be fixed with the final one. But interface class seem cannot do it ?
`class profile::mgmt_vrf
inherits ::profile::params {
  cisco_interface { 'mgmt0':
    ensure       => present,
    ipv4_address => $::profile::params::my_mgmt_ip,
    vrf          => 'management',
  }
`

`Error: /Stage[main]/Profile::Mgmt_vrf/Cisco_interface[mgmt0]: Could not evaluate: Management interfaces can be displayed but not configured
Notice: Applied catalog in 15.28 seconds`

Thanks for you great work !

**Comment by mikewiebe** [comment]
@JBaptisme This is correct.  We intentionally added the following check when using the `cisco_interface` provider.

https://github.com/cisco/cisco-network-puppet-module/blob/5a786f051c66702fa6137a1f00c5cdb6784ce4fc/lib/puppet/provider/cisco_interface/cisco.rb#L371

If you would like to configure the ip address on the mgmt interface then you could use `cisco_config` instead.

```puppet
  cisco_command_config { 'management_interface':
    command => "
      interface mgmt0
        description configured by puppet 
        ip address 192.168.1.42/24
    "
  }
```

**Comment by JBaptisme** [comment]
Hello @mikewiebe 
Thanks for your fast answer, I  appreciate !

Regards,
