### ISSUE TITLE
cisco_vdc - Could not evaluate: RuntimeError

### ISSUE THREAD

**Issue by pcevela** [cisco/cisco-network-puppet-module#582]
Hi, my manifest contains pretty much example configuration of cisco_vdc module:
```
  cisco_vdc { 'default':
    ensure                     => present,
    #limit_resource_module_type => 'vlan',
  }
```
Even with this minimalistic config, I'm getting:
```
Debug: Prefetching cisco resources for cisco_vdc
Notice: /Stage[main]/Main/Node[<hostname>]/Cisco_vdc[default]/ensure: created (corrective)
Error: /Stage[main]/Main/Node[<hostname>]/Cisco_vdc[default]: Could not evaluate: RuntimeError
```
Test switch is "Nexus9000 9000v Chassis".
Puppet-Agent in proxy mode is running on top of CentOS8 with latest puppet & module versions from offical repositories.

Thanks for help

**Comment by mikewiebe** [comment]
@pcevela Thanks for reporting the issue.  We will investigate and report back.  I have a few questions.

1. What image version are you running on the 9000v?
2. You indicate you are running in proxy mode.  Does this mean you are running agentless?
3. Can you also add the `--trace` option and include the debug info from the puppet run?

**Comment by chrisvanheuveln** [comment]
@pcevela The module does not support VDC management on 9000v. It's only supported on N7K platforms. Is there a use-case for 9000v?

https://github.com/cisco/cisco-network-puppet-module#type-cisco_vdc
https://github.com/cisco/cisco-network-node-utils/blob/develop/lib/cisco_node_utils/vdc.rb#L49

**Comment by pcevela** [comment]
Hi guys,
I verified it with our architect and you're right, n9k doesn't have support for "vdc" function itself even though configuration block is in running config. 

Can we change this bug to RFE to handle this error more reasonably than "Runtime error" to maybe "Uncompatible platform"?

Sorry for confusion.

**Comment by chrisvanheuveln** [comment]
Sure. A failure message probably would've avoided this issue altogether. We'll add it.

**Comment by chrisvanheuveln** [comment]
https://github.com/cisco/cisco-network-node-utils/pull/652
